spring:
  application:
    name: gisa-eureka-server
server:
  port: ${PORT:8761}
eureka:
  client:
    #register eureka as application
    register-with-eureka: true
    #fetch all thing, we can get applications here
    fetch-registry: true
    #also you can specify the instance renewal time.
  server:
    enable-self-preservation: false
